name: "learning how to chain workflows with github actions"

on:
  workflow_dispatch:
    inputs:
      run-job-3:
        description: "should we run job-3?"
        required: true
        type: boolean
jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - name: job-1
        run: echo "hello from job 1"

  job-2:
    name: job-2
    runs-on: ubuntu-latest
    needs:
      job-1
    steps:
      - name: job-2
        run: echo "hello from job 2"

  job-3:
    name: job-3
    runs-on: ubuntu-latest
    if: github.event.inputs.run-job-3 == 'true'
    needs: job-1
    steps:
      - name: job-3
        run: echo "hello from job-3"

  job-4:
    name: job-4
    runs-on: ubuntu-latest
    #if: always()
    needs:
      - job-1
      - job-2
      - job-3
    steps:
      - name: job-4
        run: echo "hello from job 4"